### ISSUE TITLE
Implement bootstrap command test scenario for flag --push-to-git=true

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/kam#127]
### Describe the solution you'd like

Implement --push-to-git=true flag scenario. Check for details - https://github.com/redhat-developer/kam/issues/124#issuecomment-751435369
### Describe alternatives you've considered

NA

**Comment by bigkevmcd** [comment]
The issue here is that the /etc/passwd file and $HOME don't match, this means that if git delegates to `openssh` to establish a secure connection, openssh is using the homedir from /etc/passwd instead of $HOME and so, attempting to use `/.ssh` instead of `$HOME/.ssh`.

Push to git is not a core bit of functionality, it's a nice add-on, and we can work around it by configuring git over https and pushing to the repo's https endpoint.

**Comment by amitkrout** [comment]
https://github.com/redhat-developer/kam/pull/229#issuecomment-829883673
/close
